### ISSUE TITLE
Implement Swerve Drive for Opportunitree - teleOp

### ISSUE THREAD

**Issue by dotnetprofessional** [SaintsRobotics/frc2020#9]
Implement the subsystem to actually control the robot. This task is to have the teleOp method working. Ie 

move(x,y,rotation)

**Comment by noam987** [comment]
Right Now the Bot is driveable, but has a right drift.

**Comment by dotnetprofessional** [comment]
I think its worth putting a PR out for this now. However, create a bug (ie an Issue with a label of bug) to track the issue. We can even do any refactoring as part of a new PR. Also please reference this issue with your PR. The easiest way to do that is to include the text #9 at the start of a commit comment.
